import { grey as g, accent as a, ansi } from '../palette.mjs';
import { alpha, mix, transparent } from './color.mjs';

const accent = a.blue;
const warning = a.purple;
const surface = g.bg;
const hairline = g.hairline;
const focus = alpha(accent, 0.6);

const dim = (hex) => mix(hex, g.bg, 0.7);

// Zed fills any colour left unset from One Dark, so every schema property is set.
export const colors = {
  border: hairline,
  'border.variant': hairline,
  'border.focused': focus,
  'border.selected': accent,
  'border.transparent': transparent,
  'border.disabled': hairline,

  background: surface,
  'surface.background': surface,
  'elevated_surface.background': g.bgFloat,

  'element.background': g.bgFloat,
  'element.hover': alpha(g.fg, 0.06),
  'element.active': alpha(accent, 0.25),
  'element.selected': g.bgSelection,
  'element.disabled': g.bgFloat,
  'element.selection_background': alpha(accent, 0.35),
  'ghost_element.background': transparent,
  'ghost_element.hover': alpha(g.fg, 0.06),
  'ghost_element.active': alpha(g.fg, 0.1),
  'ghost_element.selected': g.bgSelection,
  'ghost_element.disabled': transparent,
  'drop_target.background': alpha(accent, 0.15),
  'drop_target.border': accent,

  text: g.fg,
  'text.muted': g.fgMuted,
  'text.placeholder': g.fgSubtle,
  'text.disabled': g.fgSubtle,
  'text.accent': accent,
  icon: g.fgMuted,
  'icon.muted': g.fgSubtle,
  'icon.disabled': g.lineNr,
  'icon.placeholder': g.fgSubtle,
  'icon.accent': accent,
  'link_text.hover': a.ice,
  'debugger.accent': a.pink,

  'title_bar.background': surface,
  'title_bar.inactive_background': surface,
  'status_bar.background': surface,
  'toolbar.background': surface,
  'tab_bar.background': surface,
  'tab.active_background': surface,
  'tab.inactive_background': surface,
  'panel.background': surface,
  'panel.focused_border': focus,
  'panel.indent_guide': g.guide,
  'panel.indent_guide_hover': g.fgSubtle,
  'panel.indent_guide_active': g.lineNr,
  'panel.overlay_background': surface,
  'panel.overlay_hover': g.bgFloat,
  'pane.focused_border': focus,
  'pane_group.border': hairline,

  'scrollbar.thumb.background': alpha(g.fgSubtle, 0.25),
  'scrollbar.thumb.hover_background': alpha(g.fgSubtle, 0.4),
  'scrollbar.thumb.active_background': alpha(g.fgSubtle, 0.55),
  'scrollbar.thumb.border': transparent,
  'scrollbar.track.background': transparent,
  'scrollbar.track.border': transparent,
  'minimap.thumb.background': alpha(g.fgSubtle, 0.15),
  'minimap.thumb.hover_background': alpha(g.fgSubtle, 0.25),
  'minimap.thumb.active_background': alpha(g.fgSubtle, 0.35),
  'minimap.thumb.border': transparent,

  'search.match_background': alpha(a.cyan, 0.2),
  'search.active_match_background': alpha(a.sky, 0.4),

  'editor.background': surface,
  'editor.foreground': g.fg,
  'editor.gutter.background': surface,
  'editor.subheader.background': g.bgFloat,
  'editor.active_line.background': g.bgLine,
  'editor.highlighted_line.background': alpha(accent, 0.08),
  'editor.debugger_active_line.background': alpha(warning, 0.15),
  'editor.line_number': g.lineNr,
  'editor.active_line_number': g.lineNrActive,
  'editor.hover_line_number': g.fgMuted,
  'editor.invisible': alpha(g.lineNr, 0.6),
  'editor.wrap_guide': g.guide,
  'editor.active_wrap_guide': g.lineNr,
  'editor.indent_guide': g.guide,
  'editor.indent_guide_active': g.lineNr,
  'editor.document_highlight.read_background': alpha(accent, 0.15),
  'editor.document_highlight.write_background': alpha(a.rose, 0.18),
  'editor.document_highlight.bracket_background': alpha(accent, 0.18),
  'editor.code_lens.foreground': g.fgSubtle,

  'editor.diff_hunk.added.background': alpha(a.green, 0.12),
  'editor.diff_hunk.added.hollow_background': alpha(a.green, 0.06),
  'editor.diff_hunk.added.hollow_border': alpha(a.green, 0.36),
  'editor.diff_hunk.deleted.background': alpha(a.pink, 0.12),
  'editor.diff_hunk.deleted.hollow_background': alpha(a.pink, 0.06),
  'editor.diff_hunk.deleted.hollow_border': alpha(a.pink, 0.36),

  'version_control.added': a.green,
  'version_control.deleted': a.pink,
  'version_control.modified': accent,
  'version_control.renamed': a.cyan,
  'version_control.conflict': warning,
  'version_control.ignored': g.fgSubtle,
  'version_control.word_added': alpha(a.green, 0.18),
  'version_control.word_deleted': alpha(a.pink, 0.18),
  'version_control.conflict_marker.ours': alpha(a.green, 0.12),
  'version_control.conflict_marker.theirs': alpha(accent, 0.12),

  'terminal.background': surface,
  'terminal.foreground': g.fg,
  'terminal.bright_foreground': g.fg,
  'terminal.dim_foreground': g.fgMuted,
  'terminal.ansi.background': surface,
  'terminal.ansi.black': ansi.black,
  'terminal.ansi.red': ansi.red,
  'terminal.ansi.green': ansi.green,
  'terminal.ansi.yellow': ansi.yellow,
  'terminal.ansi.blue': ansi.blue,
  'terminal.ansi.magenta': ansi.magenta,
  'terminal.ansi.cyan': ansi.cyan,
  'terminal.ansi.white': ansi.white,
  'terminal.ansi.bright_black': ansi.brightBlack,
  'terminal.ansi.bright_red': ansi.brightRed,
  'terminal.ansi.bright_green': ansi.brightGreen,
  'terminal.ansi.bright_yellow': ansi.brightYellow,
  'terminal.ansi.bright_blue': ansi.brightBlue,
  'terminal.ansi.bright_magenta': ansi.brightMagenta,
  'terminal.ansi.bright_cyan': ansi.brightCyan,
  'terminal.ansi.bright_white': ansi.brightWhite,
  'terminal.ansi.dim_black': dim(ansi.black),
  'terminal.ansi.dim_red': dim(ansi.red),
  'terminal.ansi.dim_green': dim(ansi.green),
  'terminal.ansi.dim_yellow': dim(ansi.yellow),
  'terminal.ansi.dim_blue': dim(ansi.blue),
  'terminal.ansi.dim_magenta': dim(ansi.magenta),
  'terminal.ansi.dim_cyan': dim(ansi.cyan),
  'terminal.ansi.dim_white': dim(ansi.white),

  'vim.normal.background': accent,
  'vim.normal.foreground': g.bg,
  'vim.insert.background': a.green,
  'vim.insert.foreground': g.bg,
  'vim.replace.background': a.pink,
  'vim.replace.foreground': g.bg,
  'vim.visual.background': a.purple,
  'vim.visual.foreground': g.bg,
  'vim.visual_line.background': a.purple,
  'vim.visual_line.foreground': g.bg,
  'vim.visual_block.background': a.purple,
  'vim.visual_block.foreground': g.bg,
  'vim.helix_normal.background': accent,
  'vim.helix_normal.foreground': g.bg,
  'vim.helix_select.background': a.purple,
  'vim.helix_select.foreground': g.bg,
  'vim.yank.background': alpha(a.purple, 0.3),
  'vim.helix_jump_label.foreground': a.rose,
};

const statusColor = (name, color) => ({
  [name]: color,
  [`${name}.background`]: alpha(color, 0.12),
  [`${name}.border`]: alpha(color, 0.5),
});

export const status = {
  ...statusColor('error', a.pink),
  ...statusColor('warning', warning),
  ...statusColor('info', accent),
  ...statusColor('hint', a.teal),
  ...statusColor('success', a.green),
  ...statusColor('created', a.green),
  ...statusColor('modified', accent),
  ...statusColor('deleted', a.pink),
  ...statusColor('renamed', a.cyan),
  ...statusColor('conflict', warning),
  ...statusColor('ignored', g.fgSubtle),
  ...statusColor('hidden', g.fgSubtle),
  ...statusColor('unreachable', g.fgSubtle),
  ...statusColor('predictive', g.fgSubtle),
};

const collaborator = (color) => ({ cursor: color, background: color, selection: alpha(color, 0.25) });
export const players = [
  // Translucent (≈ bgSelection over bg): Zed paints selections above search and symbol highlights.
  { cursor: g.fg, background: accent, selection: alpha(g.fg, 0.13) },
  collaborator(a.pink),
  collaborator(a.green),
  collaborator(a.purple),
  collaborator(a.cyan),
  collaborator(a.rose),
  collaborator(a.ice),
  collaborator(a.teal),
];

export const accents = [a.blue, a.purple, a.cyan, a.rose, a.ice, a.green];
