// TextMate token rules.
import { grey, accent, syntax as s } from './palette.mjs';

const rule = (name, scope, foreground, fontStyle) => {
  const settings = {};
  if (foreground) settings.foreground = foreground;
  // Always set fontStyle: a rule without one inherits bold/italic from a less
  // specific rule for a parent scope.
  settings.fontStyle = fontStyle ?? '';
  return { name, scope, settings };
};

export default [
  // Base
  rule('Comments', ['comment', 'punctuation.definition.comment', 'string.comment'], s.comment, 'italic'),
  rule(
    'Doc comments',
    ['comment.block.documentation', 'comment.line.documentation', 'comment.line.double-slash.documentation', 'comment.line.triple-slash', 'comment.block.documentation punctuation.definition.comment', 'comment.line.documentation punctuation.definition.comment'],
    s.docComment,
    'italic',
  ),
  rule(
    'Doc comment tags',
    [
      'comment.block.documentation storage.type',
      'comment.block.documentation punctuation.definition.block.tag',
      'comment.block.documentation keyword',
      'storage.type.class.jsdoc',
      'punctuation.definition.block.tag.jsdoc',
      'storage.type.class.doxygen',
      'storage.type.class.gtkdoc',
    ],
    grey.fgMuted,
    'italic',
  ),
  rule(
    'Doc comment types and names',
    ['entity.name.type.instance.jsdoc', 'variable.other.jsdoc', 'comment.block.documentation entity.name.type', 'comment.block.documentation variable', 'comment.block.documentation variable.other'],
    grey.fgMuted,
    'italic',
  ),
  rule(
    'TODO / FIXME',
    ['keyword.codetag.notation', 'comment keyword.other.todo', 'comment storage.type.class.todo', 'comment markup.bold'],
    s.todo,
    'bold italic',
  ),
  rule('Invalid', ['invalid', 'invalid.illegal'], s.invalid),
  rule('Deprecated', ['invalid.deprecated'], s.invalid, 'strikethrough'),

  // Keywords
  rule('Keywords', ['keyword', 'keyword.other'], s.keyword),
  // Control flow and imports are italic; declaration keywords stay upright.
  rule(
    'Control-flow keywords',
    ['keyword.control', 'keyword.other.using', 'keyword.other.import', 'keyword.control.flow', 'keyword.control.conditional', 'keyword.control.loop', 'keyword.control.trycatch', 'keyword.control.switch', 'keyword.control.exception'],
    s.keyword,
    'italic',
  ),
  rule(
    'Storage and declaration keywords',
    [
      'storage',
      'storage.type',
      'storage.modifier',
      'keyword.declaration',
      'keyword.other.fn.rust',
      'keyword.other.rust',
      'keyword.function.go',
      'keyword.var.go',
      'keyword.const.go',
      'keyword.type.go',
      'keyword.struct.go',
      'keyword.interface.go',
      'keyword.map.go',
      'keyword.channel.go',
      'keyword.other.typedef',
      'keyword.other.alias',
      'keyword.other.var',
      'keyword.other.let',
      'keyword.other.def',
      'keyword.other.class',
      'keyword.other.struct',
      'keyword.other.enum',
      'keyword.other.fn',
      'keyword.other.type',
      'storage.type.function.arrow',
      'keyword.generator.asterisk',
    ],
    s.storage,
  ),
  rule(
    'Imports and exports',
    ['keyword.control.import', 'keyword.control.from', 'keyword.control.export', 'keyword.control.default', 'keyword.import.go'],
    s.keyword,
    'italic',
  ),
  rule('Package and module declarations', ['keyword.package.go'], s.keyword),
  // The Rust grammar scopes `use` like `impl`; keep rust-analyzer's colour, add the italic.
  rule('Rust use', ['meta.use.rust keyword.other.rust'], s.storage, 'italic'),
  // Grammars that scope declarations as keyword.control.
  rule(
    'Declarations scoped as control keywords',
    ['keyword.control.def.ruby', 'keyword.control.class.ruby', 'keyword.control.module.ruby', 'meta.function.lua keyword.control.lua'],
    s.storage,
  ),
  rule(
    'Operators',
    ['keyword.operator', 'keyword.operator.assignment', 'keyword.operator.arithmetic', 'keyword.operator.comparison', 'keyword.operator.relational', 'keyword.operator.logical', 'keyword.operator.bitwise', 'keyword.operator.ternary', 'keyword.operator.optional', 'keyword.operator.spread', 'keyword.operator.rest', 'keyword.operator.type', 'keyword.operator.borrow', 'keyword.operator.dereference', 'keyword.operator.pipe', 'keyword.operator.redirect', 'keyword.operator.heredoc', 'punctuation.definition.function.return-type', 'punctuation.definition.lambda.return-type', 'punctuation.vararg-ellipses'],
    s.operator,
  ),
  rule(
    'Word operators',
    ['keyword.operator.new', 'keyword.operator.expression', 'keyword.operator.sizeof', 'keyword.operator.cast', 'keyword.operator.instanceof', 'keyword.operator.typeof', 'keyword.operator.delete', 'keyword.operator.alignas', 'keyword.operator.alignof', 'keyword.operator.typeid', 'keyword.operator.noexcept'],
    s.keyword,
  ),
  rule(
    'Logical and membership word operators',
    ['keyword.operator.logical.python', 'keyword.operator.word', 'keyword.operator.in', 'keyword.operator.of', 'keyword.operator.expression.in', 'keyword.operator.expression.of', 'keyword.operator.expression.is', 'keyword.operator.and', 'keyword.operator.or', 'keyword.operator.not'],
    s.keyword,
    'italic',
  ),
  rule('Preprocessor directives', ['keyword.control.directive', 'punctuation.definition.directive', 'meta.preprocessor keyword', 'keyword.other.preprocessor'], s.macro),
  rule('Include directives', ['keyword.control.directive.include', 'keyword.control.directive.import', 'entity.name.other.preprocessor.macro.predefined'], s.macro),

  // Punctuation
  rule(
    'Delimiters',
    [
      'punctuation.separator',
      'punctuation.terminator',
      'punctuation.separator.comma',
      'punctuation.separator.delimiter',
      'punctuation.separator.key-value',
      'punctuation.separator.dictionary',
      'punctuation.separator.parameters',
      'punctuation.separator.namespace',
      'punctuation.separator.colon',
      'punctuation.accessor',
      'punctuation.terminator.statement',
      'punctuation.separator.statement',
      'punctuation.other.comma',
      'punctuation.other.period',
      'punctuation.other.colon',
      'punctuation.comma',
      'punctuation.semi',
      'punctuation.colon',
      'keyword.operator.type.annotation',
      'keyword.operator.accessor',
      'punctuation.separator.annotation',
      'keyword.operator.namespace',
      'keyword.operator.access',
      'keyword.operator.key-value',
      'punctuation.destructuring',
    ],
    s.punctuation,
  ),
  rule(
    'Brackets',
    [
      'meta.brace',
      'punctuation.bracket',
      'punctuation.brackets',
      'punctuation.section',
      'punctuation.parenthesis',
      'punctuation.definition.block',
      'punctuation.definition.parameters',
      'punctuation.definition.arguments',
      'punctuation.definition.array',
      'punctuation.definition.dict',
      'punctuation.definition.list',
      'punctuation.definition.tuple',
      'punctuation.definition.typeparameters',
      'punctuation.definition.binding-pattern',
      'punctuation.definition.group',
      'punctuation.definition.bracket',
      'punctuation.definition.begin.bracket',
      'punctuation.definition.end.bracket',
      'punctuation.definition.generic',
      'punctuation.definition.imports',
      'punctuation.definition.dictionary',
      'punctuation.definition.sequence',
      'punctuation.definition.mapping',
      'punctuation.definition.section.begin.toml',
      'punctuation.definition.section.end.toml',
      'punctuation.definition.logical-expression',
      'punctuation.definition.inheritance',
    ],
    s.punctuation,
  ),
  rule('Tag brackets', ['punctuation.definition.tag', 'punctuation.definition.tag.begin', 'punctuation.definition.tag.end'], s.punctuation),
  rule(
    'Interpolation',
    [
      'punctuation.definition.template-expression',
      'punctuation.section.embedded',
      'punctuation.definition.interpolation',
      'punctuation.section.interpolation',
      'punctuation.definition.evaluation.shell',
      'punctuation.definition.subshell.shell',
      'string.interpolated punctuation.definition.string.begin.shell',
    ],
    s.storage,
  ),
  rule('Embedded code', ['meta.template.expression', 'meta.embedded.line', 'meta.interpolation', 'source.css.embedded'], s.variable),

  // Strings
  rule('Strings', ['string', 'punctuation.definition.string', 'string.template', 'string.quoted', 'string.unquoted', 'constant.character', 'string.other'], s.string),
  rule('Escapes', ['constant.character.escape', 'constant.character.entity', 'constant.character.entity punctuation.definition.entity', 'punctuation.definition.entity.html', 'constant.character.string.escape'], s.escape),
  rule(
    'Format placeholders',
    ['constant.other.placeholder', 'constant.character.format.placeholder', 'constant.other.format-spec', 'string constant.other.placeholder', 'storage.type.format', 'meta.format.percent', 'meta.format.brace'],
    s.escape,
  ),
  rule('Regular expressions', ['string.regexp', 'source.regexp', 'punctuation.definition.string.regexp', 'string.regexp punctuation.definition.string', 'string.regexp keyword.other'], s.regex),
  rule(
    'Regex internals',
    ['constant.other.character-class.regexp', 'constant.character.character-class.regexp', 'constant.other.character-class.set.regexp', 'constant.character.set.regexp', 'string.regexp constant.character.escape', 'support.other.escape.special.regexp', 'support.other.match.any.regexp', 'entity.name.tag.backreference.regexp', 'constant.other.character-class.range.regexp', 'constant.character.numeric.regexp', 'keyword.other.back-reference.regexp'],
    s.escape,
  ),
  rule('Regex quantifiers and anchors', ['keyword.operator.quantifier.regexp', 'keyword.control.anchor.regexp', 'keyword.operator.or.regexp', 'keyword.operator.negation.regexp', 'support.other.match.begin.regexp', 'support.other.match.end.regexp'], s.operator),
  rule('Regex groups', ['punctuation.definition.group.regexp', 'punctuation.definition.group.assertion.regexp', 'punctuation.definition.character-class.regexp', 'meta.assertion.look-ahead.regexp', 'meta.assertion.look-behind.regexp', 'constant.other.set.regexp', 'punctuation.character.set.begin.regexp', 'punctuation.character.set.end.regexp', 'string.regexp punctuation.parenthesis', 'entity.name.tag.named.group.regexp', 'keyword.operator.lookahead', 'keyword.operator.lookbehind', 'punctuation.definition.group.no-capture.regexp', 'variable.other.regexp'], s.storage),

  // Constants
  rule('Numbers', ['constant.numeric', 'keyword.other.unit', 'keyword.other.suffix', 'punctuation.separator.dot.decimal', 'punctuation.separator.decimal', 'constant.other.date', 'constant.other.time', 'constant.other.datetime', 'constant.other.time.datetime', 'constant.numeric punctuation', 'constant.other.color', 'constant.other.color.rgb-value', 'constant.other.rgb-value', 'storage.type.number.python', 'storage.type.imaginary.number.python', 'storage.type.numeric.bigint'], s.number),
  rule('Built-in constants', ['support.constant', 'constant.builtin', 'variable.language.ellipsis', 'constant.other.ellipsis.python'], s.builtin),
  rule('Language literals', ['constant.language', 'constant.language.boolean', 'constant.language.null', 'constant.language.undefined', 'constant.language.nil', 'constant.language.python', 'constant.language.go', 'constant.language.json', 'constant.language.bool.rust'], s.builtin, 'italic'),
  rule(
    'User constants',
    [
      'constant',
      'constant.other',
      'constant.other.caps',
      'constant.other.caps.python',
      'constant.other.caps.rust',
      'entity.name.constant',
      'variable.other.constant',
      'variable.other.enummember',
      'variable.other.enummember.ts',
      'constant.other.enum',
      'variable.other.constant.go',
      'constant.other.symbol',
      'constant.other.key',
    ],
    s.constant,
  ),
  // In JS/TS, `const` declarations are scoped variable.other.constant. They are
  // most variables in modern code, so keep them looking like variables.
  rule('JS/TS const variables', ['variable.other.constant.js', 'variable.other.constant.ts', 'variable.other.constant.tsx', 'variable.other.constant.jsx', 'variable.other.constant.object.js', 'variable.other.constant.object.ts', 'variable.other.constant.object.tsx', 'variable.other.constant.object.jsx', 'variable.other.constant.property'], s.variable),
  rule('Built-in support constants', ['support.constant.property-value', 'support.constant.font-name', 'support.constant.media', 'support.constant.vendored', 'support.constant.color'], s.builtin),

  // Variables
  rule('Variables', ['variable', 'variable.other', 'variable.other.readwrite', 'variable.other.local', 'variable.other.object', 'entity.name.variable', 'meta.definition.variable.name', 'support.variable.object'], s.variable),
  rule('Parameters', ['variable.parameter', 'meta.parameter variable', 'meta.function.parameters variable', 'entity.name.variable.parameter', 'meta.parameters.python variable'], s.parameter, 'italic'),
  rule(
    'this / self / super',
    ['variable.language', 'variable.language.this', 'variable.language.self', 'variable.language.super', 'variable.language.special.self', 'variable.parameter.function.language.special.self', 'variable.parameter.function.language.special.cls', 'variable.language.special.cls', 'variable.language.self.rust'],
    s.self,
    'italic',
  ),
  rule(
    'Properties and object keys',
    [
      'variable.other.property',
      'variable.other.object.property',
      'variable.other.member',
      'variable.other.field',
      'entity.name.variable.field',
      'entity.name.variable.property',
      'meta.object-literal.key',
      'support.variable.property',
      'support.type.property-name',
      'meta.property.object',
      'variable.object.property',
      'entity.name.tag.yaml',
      'variable.other.key.toml',
      'support.type.property-name.toml',
      'string.json support.type.property-name',
      'meta.attribute.python',
      'variable.other.declaration-property',
      'entity.other.attribute-name.table.key.toml',
    ],
    s.property,
  ),
  rule('Built-in variables', ['support.variable', 'variable.language.special', 'variable.other.predefined', 'support.variable.dom', 'support.variable.magic.python', 'support.variable.env'], s.builtin),
  rule('Shell variables', ['variable.other.normal.shell', 'variable.other.positional.shell', 'variable.other.bracket.shell', 'variable.other.special.shell', 'punctuation.definition.variable.shell', 'variable.other.assignment.shell', 'variable.parameter.positional.shell', 'variable.parameter.positional.all.shell'], s.property),

  // Functions
  rule('Function calls', ['entity.name.function', 'support.function', 'meta.function-call entity.name.function', 'meta.function-call.generic', 'variable.function', 'entity.name.function.call', 'entity.name.command.shell', 'support.function.builtin.shell'], s.function, ''),
  rule('Built-in functions', ['support.function.builtin', 'support.function.builtin.python', 'support.function.console', 'support.function.std'], s.builtin),
  rule(
    'Function declarations',
    [
      'meta.definition.function entity.name.function',
      'meta.function.python entity.name.function',
      'meta.function.definition.rust entity.name.function.rust',
      'meta.definition.variable entity.name.function',
      'entity.name.function.definition',
      'entity.name.function.shell',
    ],
    s.function,
    'bold',
  ),
  rule('Method calls', ['entity.name.function.member', 'entity.name.function.method', 'meta.method-call entity.name.function', 'support.function.dom', 'variable.function.member'], s.method, ''),
  rule('Method declarations', ['meta.definition.method entity.name.function', 'entity.name.function.method.definition', 'entity.name.function.member.definition'], s.method, 'bold'),
  rule('Constructors', ['entity.name.function.constructor', 'entity.name.function.definition.special.constructor', 'entity.name.function.definition.special.member.destructor'], s.type, 'bold'),
  rule('Macros', ['entity.name.function.macro', 'entity.name.function.preprocessor', 'meta.preprocessor.macro entity.name.function', 'support.macro', 'entity.name.macro', 'meta.macro.rust entity.name.function', 'support.function.macro'], s.macro),
  rule('Decorators and attributes', ['meta.decorator', 'punctuation.decorator', 'meta.decorator entity.name.function', 'meta.decorator meta.function-call entity.name.function', 'meta.decorator variable.other', 'meta.function.decorator', 'meta.function.decorator support.type', 'meta.function.decorator.python support.type.python', 'meta.function.decorator support.function', 'meta.function.decorator entity.name.function', 'entity.name.function.decorator', 'punctuation.definition.decorator', 'meta.attribute.rust', 'punctuation.definition.attribute.rust', 'storage.type.annotation', 'punctuation.definition.annotation', 'meta.annotation', 'entity.name.function.attribute'], s.decorator),

  // Types
  rule(
    'Types',
    [
      'entity.name.type',
      'entity.name.class',
      'entity.name.struct',
      'entity.name.enum',
      'entity.name.union',
      'entity.name.interface',
      'entity.name.type.class',
      'entity.name.type.struct',
      'entity.name.type.enum',
      'entity.name.type.alias',
      'entity.other.inherited-class',
      'support.class',
      'support.type',
      'storage.type.cs',
      'storage.type.java',
      'meta.type.annotation entity.name.type',
      'entity.name.type.rust',
      'entity.name.type.go',
      'entity.name.type.cpp',
      'entity.name.scope-resolution.template-call',
    ],
    s.type,
  ),
  rule(
    'Built-in types',
    [
      'support.type.primitive',
      'support.type.builtin',
      'support.type.built-in',
      'support.type.python',
      'storage.type.primitive',
      'storage.type.built-in',
      'storage.type.built-in.primitive',
      'storage.type.numeric',
      'storage.type.string',
      'storage.type.boolean',
      'storage.type.byte.go',
      'storage.type.rune.go',
      'storage.type.error.go',
      'storage.type.uintptr.go',
      'entity.name.type.primitive',
      'entity.name.type.numeric',
      'entity.name.type.primitive.rust',
      'entity.name.type.numeric.rust',
      'support.type.posix-reserved',
      'support.type.sys-types',
      'support.type.stdint',
      'storage.type.integral',
      'support.class.builtin',
      'support.class.promise',
      'support.class.error',
      'support.type.exception',
      'support.type.exception.python',
    ],
    s.type,
    'italic',
  ),
  rule(
    'Type parameters',
    ['entity.name.type.parameter', 'meta.type.parameters entity.name.type', 'entity.name.type.template', 'storage.type.template.argument'],
    s.type,
    'italic',
  ),
  // C++ scopes the type of a function parameter as entity.name.type.parameter.
  rule('Trait and interface declarations', ['entity.name.type.trait', 'entity.name.type.interface'], s.type, 'italic'),
  rule('C++ lambda return types', ['storage.type.return-type.lambda'], s.type),
  rule('C++ parameter types', ['entity.name.type.parameter.cpp', 'entity.name.type.parameter.c'], s.type),
  rule('C++ template keywords', ['storage.type.template.argument.typename', 'storage.type.template.argument.class'], s.storage),
  rule('Lifetimes', ['punctuation.definition.lifetime.rust', 'entity.name.type.lifetime', 'entity.name.type.lifetime.rust'], s.lifetime, 'italic'),
  // "struct", "class", "enum" in C/C++ are storage keywords, not type names.
  rule('Declaration keywords that grammars scope as types', ['storage.type.struct', 'storage.type.class', 'storage.type.enum', 'storage.type.union', 'storage.type.interface', 'storage.type.type', 'storage.type.function', 'storage.type.namespace', 'storage.type.template', 'storage.type.typedef', 'storage.type.class.python', 'storage.type.function.python', 'storage.type.rust', 'storage.type.ts', 'storage.type.js', 'storage.type.property'], s.storage),

  // Namespaces
  rule(
    'Namespaces and modules',
    [
      'entity.name.namespace',
      'entity.name.module',
      'entity.name.type.module',
      'entity.name.type.namespace',
      'entity.name.package',
      'entity.name.import.go',
      'entity.name.package.go',
      'entity.name.scope-resolution',
      'support.other.namespace',
      'support.other.module',
      'meta.import.module',
      'entity.name.type.package',
      'storage.modifier.import.java',
      'storage.modifier.package.java',
      'meta.path.rust entity.name.namespace',
      'variable.other.namespace',
    ],
    s.namespace,
  ),
  rule('Labels', ['entity.name.label', 'entity.name.goto-label', 'punctuation.definition.label'], s.label),

  // HTML / JSX / XML
  rule('Tags', ['entity.name.tag', 'meta.tag.sgml', 'entity.name.tag.html', 'entity.name.tag.xml', 'entity.name.tag.js', 'entity.name.tag.tsx'], s.tag),
  rule('Component tags', ['support.class.component', 'entity.name.tag.component', 'entity.name.tag.custom', 'entity.name.tag.other'], s.type),
  rule('Tag attributes', ['entity.other.attribute-name', 'entity.other.attribute-name.html', 'entity.other.attribute-name.jsx', 'entity.other.attribute-name.tsx', 'entity.other.attribute-name.localname.xml'], s.attribute),
  rule('Doctype', ['meta.tag.metadata.doctype', 'meta.tag.sgml.doctype', 'entity.name.tag.doctype', 'meta.tag.preprocessor.xml'], grey.fgMuted),

  // CSS / SCSS / Less
  rule('CSS tag selectors', ['entity.name.tag.css', 'entity.name.tag.scss', 'entity.name.tag.less', 'entity.name.tag.wildcard.css'], s.tag),
  rule('CSS class selectors', ['entity.other.attribute-name.class.css', 'entity.other.attribute-name.class', 'entity.other.attribute-name.class punctuation.definition.entity', 'entity.other.attribute-name.parent-selector'], s.type),
  rule('CSS id selectors', ['entity.other.attribute-name.id.css', 'entity.other.attribute-name.id', 'entity.other.attribute-name.id punctuation.definition.entity'], accent.rose),
  rule('CSS pseudo selectors', ['entity.other.attribute-name.pseudo-class', 'entity.other.attribute-name.pseudo-element', 'entity.other.attribute-name.pseudo-class.css', 'entity.other.attribute-name.pseudo-element.css', 'entity.other.attribute-name.pseudo-class punctuation.definition.entity', 'entity.other.attribute-name.pseudo-element punctuation.definition.entity'], s.method),
  rule('CSS attribute selectors', ['meta.attribute-selector.css entity.other.attribute-name.attribute'], s.attribute),
  rule('CSS properties', ['support.type.property-name.css', 'support.type.property-name.scss', 'support.type.property-name.less', 'support.type.vendored.property-name', 'meta.property-name.scss'], s.property),
  rule('CSS custom properties', ['variable.css', 'variable.scss', 'variable.less', 'variable.argument.css', 'support.type.custom-property', 'support.type.custom-property.name', 'punctuation.definition.custom-property'], s.property, 'italic'),
  rule('CSS functions', ['support.function.misc.css', 'support.function.transform.css', 'support.function.url.css', 'support.function.calc.css', 'support.function.var.css'], s.function),
  rule('CSS at-rules', ['keyword.control.at-rule', 'punctuation.definition.keyword', 'keyword.control.at-rule.css', 'keyword.control.at-rule punctuation.definition.keyword'], s.keyword),
  rule('CSS important', ['keyword.other.important'], s.self, 'bold'),

  // JSON
  rule('JSON keys', ['support.type.property-name.json', 'meta.structure.dictionary.json support.type.property-name', 'support.type.property-name.json punctuation.support.type.property-name'], s.property),
  rule('JSON strings', ['meta.structure.dictionary.value.json string.quoted.double', 'string.quoted.double.json'], s.string),

  // YAML
  rule('YAML anchors and aliases', ['entity.name.type.anchor.yaml', 'variable.other.alias.yaml', 'punctuation.definition.anchor.yaml', 'punctuation.definition.alias.yaml'], s.self),
  rule('YAML tags', ['storage.type.tag-handle.yaml', 'keyword.other.tag.local.yaml'], s.storage),
  rule('YAML document markers', ['entity.other.document.begin.yaml', 'entity.other.document.end.yaml', 'punctuation.definition.block.sequence.item.yaml'], grey.fgMuted),
  rule('YAML block scalars', ['keyword.control.flow.block-scalar.literal.yaml', 'keyword.control.flow.block-scalar.folded.yaml'], s.operator),

  // TOML
  rule('TOML tables', ['entity.other.attribute-name.table.toml', 'entity.other.attribute-name.table.array.toml', 'support.type.property-name.table.toml', 'support.type.property-name.array.toml', 'entity.name.section.toml'], s.type, 'bold'),
  rule('TOML table brackets', ['punctuation.definition.table.toml', 'punctuation.definition.table.array.toml'], s.punctuation),

  // INI / dotenv
  rule('INI sections', ['entity.name.section.group-title.ini'], s.type, 'bold'),
  rule('INI keys', ['keyword.other.definition.ini'], s.property),

  // Markdown
  rule('Headings', ['markup.heading', 'entity.name.section.markdown', 'markup.heading.markdown', 'markup.heading entity.name', 'markup.heading.setext'], s.heading, 'bold'),
  rule('Heading markers', ['punctuation.definition.heading.markdown'], s.heading, 'bold'),
  rule('Bold', ['markup.bold', 'punctuation.definition.bold.markdown'], s.bold, 'bold'),
  rule('Italic', ['markup.italic', 'punctuation.definition.italic.markdown'], s.variable, 'italic'),
  rule('Bold italic', ['markup.bold markup.italic', 'markup.italic markup.bold'], s.bold, 'bold italic'),
  rule('Strikethrough', ['markup.strikethrough'], grey.fgMuted, 'strikethrough'),
  rule('Inline code', ['markup.inline.raw', 'markup.inline.raw.string.markdown', 'markup.raw', 'markup.raw.inline'], s.string),
  rule('Code fences', ['markup.fenced_code.block.markdown punctuation.definition.markdown', 'punctuation.definition.raw.markdown', 'markup.raw.block.markdown'], grey.fgMuted),
  rule('Code fence language', ['fenced_code.block.language', 'fenced_code.block.language.markdown', 'fenced_code.block.language.attributes'], s.namespace),
  rule('Link text', ['string.other.link.title.markdown', 'string.other.link.description.markdown', 'string.other.link.description.title.markdown', 'meta.link.inline.markdown string.other.link', 'constant.other.reference.link.markdown', 'meta.image.inline.markdown string.other.link'], s.link),
  rule('Link URLs', ['markup.underline.link', 'markup.underline.link.markdown', 'markup.underline.link.image.markdown', 'meta.link.inline.markdown markup.underline.link', 'string.other.link'], s.property, 'underline'),
  rule('Link brackets', ['punctuation.definition.link.title.begin.markdown', 'punctuation.definition.link.title.end.markdown', 'punctuation.definition.link.description.begin.markdown', 'punctuation.definition.link.description.end.markdown', 'punctuation.definition.metadata.markdown', 'punctuation.definition.link.markdown'], grey.fgMuted),
  rule('Quotes', ['markup.quote', 'markup.quote.markdown', 'punctuation.definition.quote.begin.markdown'], grey.fgMuted, 'italic'),
  rule('List markers', ['punctuation.definition.list.begin.markdown', 'beginning.punctuation.definition.list.markdown', 'beginning.punctuation.definition.quote.markdown', 'punctuation.definition.list_item.markdown'], s.storage),
  rule('Horizontal rules', ['meta.separator.markdown', 'meta.separator'], grey.fgMuted),
  rule('Tables', ['punctuation.definition.table.markdown', 'markup.table punctuation'], grey.fgMuted),
  rule('Front matter', ['meta.embedded.block.frontmatter', 'punctuation.definition.tag.frontmatter'], grey.fgMuted),

  // Diff
  rule('Diff inserted', ['markup.inserted', 'meta.diff.header.to-file', 'punctuation.definition.inserted'], s.inserted),
  rule('Diff deleted', ['markup.deleted', 'meta.diff.header.from-file', 'punctuation.definition.deleted'], s.deleted),
  rule('Diff changed', ['markup.changed', 'punctuation.definition.changed'], s.changed),
  rule('Diff ranges', ['meta.diff.range', 'meta.diff.index', 'meta.separator.diff', 'meta.diff.header'], s.namespace),

  // Git
  rule('Git commit subject', ['meta.scope.message.git-commit', 'markup.heading.git-commit'], s.variable),
  rule('Git rebase commands', ['support.function.git-rebase'], s.keyword),
  rule('Git rebase hashes', ['constant.sha.git-rebase'], s.number),

  // Shared across languages
  rule('Interpolation contents', ['meta.fstring.python constant.character.format.placeholder.other.python'], s.interpolation),
  rule('Property declarations and object keys', ['meta.object-literal.key', 'meta.definition.property variable.object.property', 'meta.field.declaration variable.object.property'], s.propertyDeclaration),
  rule('Optional chaining', ['punctuation.accessor.optional'], s.operator),
  rule('Case labels', ['punctuation.definition.section.case-statement'], s.punctuation),

  // Python
  rule('String prefixes', ['storage.type.string.python', 'string.quoted.byte.raw.rust'], s.storage),
  rule('Python format specs', ['storage.type.format.python', 'meta.fstring.python storage.type.format.python'], s.escape),
  rule('Python docstrings', ['string.quoted.docstring', 'string.quoted.docstring punctuation.definition.string'], s.string, 'italic'),
  rule('Python magic methods', ['support.function.magic.python', 'meta.function.python support.function.magic.python'], s.method),
  rule('Python method calls', ['meta.member.access.python meta.function-call.generic.python'], s.method),
  rule('Python keyword arguments', ['variable.parameter.function-call.python', 'meta.function-call.arguments.python variable.parameter'], s.parameter, 'italic'),

  // TypeScript / JavaScript
  rule('Decorator names', ['meta.decorator variable.other.readwrite', 'meta.decorator variable.other.readwrite.ts', 'meta.decorator variable.other.readwrite.tsx', 'meta.decorator entity.name.function.ts', 'meta.decorator entity.name.function.tsx'], s.decorator),
  rule('Constructor calls', ['new.expr entity.name.function', 'new.expr meta.function-call entity.name.function', 'new.expr entity.name.type'], s.type),

  // Rust
  rule('Rust references', ['keyword.operator.borrow.rust', 'keyword.operator.borrow.and.rust', 'keyword.operator.dereference.rust'], s.operator),
  rule('Rust mut / ref', ['storage.modifier.mut.rust'], s.storage),
  rule('Rust ? operator', ['keyword.operator.question.rust'], s.keyword, 'bold'),
  rule('Rust macros', ['entity.name.function.macro.rust', 'meta.macro.rules.rust entity.name.function.macro.rust'], s.macro),
  rule('Rust macro_rules!', ['entity.name.function.macro.rules.rust'], s.storage),
  rule('Rust macro metavariables', ['variable.other.metavariable.name.rust', 'keyword.operator.macro.dollar.rust'], s.macro, 'italic'),
  rule('Rust macro fragment specifiers', ['variable.other.metavariable.specifier.rust'], s.type, 'italic'),
  rule('Rust attribute contents', ['punctuation.brackets.attribute.rust', 'meta.attribute.rust entity.name.type.rust', 'meta.attribute.rust variable.other.rust', 'meta.attribute.rust keyword.operator'], s.decorator),
  rule('Rust attribute arguments', ['meta.attribute.rust punctuation.brackets.round.rust', 'meta.attribute.rust punctuation.comma.rust'], s.punctuation),
  rule('Rust attribute strings', ['meta.attribute.rust string', 'meta.attribute.rust string punctuation.definition.string'], s.string),
  rule('Rust Option and Result variants', ['entity.name.type.option.rust', 'entity.name.type.result.rust'], s.constant),
  rule('Rust numeric suffixes', ['constant.numeric entity.name.type.numeric.rust', 'constant.numeric.decimal.rust entity.name.type.numeric.rust', 'constant.numeric.hex.rust entity.name.type.numeric.rust'], s.number),

  // C / C++
  rule('C/C++ pointers and references', ['storage.modifier.pointer', 'storage.modifier.reference', 'keyword.operator.pointer'], s.operator),
  rule('C/C++ include paths', ['string.quoted.other.lt-gt.include', 'meta.preprocessor.include string'], s.string),
  rule('C/C++ macro calls', ['entity.name.function.call.upper-case entity.name.function.call', 'entity.name.function.call.upper-case.cpp entity.name.function.call.cpp', 'entity.name.function.call.upper-case.c entity.name.function.call.c'], s.macro),
  rule('C++ attributes', ['support.other.attribute', 'support.other.attribute punctuation.section.attribute', 'entity.other.attribute'], s.decorator),
  rule('C++ operator overloads', ['entity.name.operator', 'entity.name.operator.cpp'], s.function, 'bold'),
  rule('C++ declaration keywords', ['keyword.other.operator.overload', 'keyword.other.concept', 'meta.declaration.type.alias keyword.other.using.directive'], s.storage),
  rule('C++ lambda captures', ['punctuation.definition.capture.begin.lambda', 'punctuation.definition.capture.end.lambda'], s.punctuation),
  rule('C++ raw strings', ['string.quoted.double.raw', 'punctuation.definition.string.raw'], s.string),
  rule('C++ string prefixes', ['meta.encoding', 'punctuation.definition.string.begin meta.encoding'], s.storage),

  rule('Go struct field', ['variable.other.field.go', 'variable.other.property.field.go'], s.property),
  rule('Command-line options', ['constant.other.option', 'string.unquoted.argument.shell constant.other.option', 'constant.other.option.dash.shell'], s.attribute),
  rule('Shell heredoc delimiters', ['keyword.control.heredoc-token.shell', 'punctuation.definition.string.heredoc'], s.storage),
  rule('Shell shebang', ['comment.line.shebang', 'punctuation.definition.comment.shebang'], grey.fgMuted, 'italic'),
];
