// Workbench (UI) colours.
import { grey as g, accent as a, ansi } from './palette.mjs';

// Append a two-digit hex alpha to a #rrggbb colour.
const alpha = (hex, opacity) =>
  hex +
  Math.round(opacity * 255)
    .toString(16)
    .padStart(2, '0');

const accent = a.blue;
const alert = a.pink;
const transparent = '#00000000';

export default {
  // Base
  foreground: g.fg,
  disabledForeground: g.fgSubtle,
  descriptionForeground: g.fgMuted,
  errorForeground: a.pink,
  focusBorder: alpha(accent, 0.6),
  'widget.border': g.border,
  'widget.shadow': '#00000066',
  'selection.background': alpha(accent, 0.35),
  'icon.foreground': g.fgMuted,
  'sash.hoverBorder': accent,
  'textLink.foreground': accent,
  'textLink.activeForeground': a.ice,
  'textBlockQuote.background': g.bgFloat,
  'textBlockQuote.border': g.border,
  'textCodeBlock.background': g.bgFloat,
  'textPreformat.foreground': a.purple,
  'textPreformat.background': g.bgFloat,
  'textSeparator.foreground': g.border,
  'toolbar.hoverBackground': g.bgSelection,
  'toolbar.activeBackground': g.bgSelection,
  'progressBar.background': accent,

  // Window
  'window.activeBorder': g.border,
  'window.inactiveBorder': g.border,

  // Title bar
  'titleBar.activeBackground': g.bgDark,
  'titleBar.activeForeground': g.fg,
  'titleBar.inactiveBackground': g.bgDark,
  'titleBar.inactiveForeground': g.fgSubtle,
  'titleBar.border': g.border,
  'commandCenter.background': g.bgFloat,
  'commandCenter.foreground': g.fgMuted,
  'commandCenter.activeBackground': g.bgSelection,
  'commandCenter.activeForeground': g.fg,
  'commandCenter.border': g.border,
  'commandCenter.activeBorder': g.border,
  'commandCenter.inactiveForeground': g.fgSubtle,
  'commandCenter.inactiveBorder': g.border,

  // Menus
  'menubar.selectionBackground': g.bgSelection,
  'menubar.selectionForeground': g.fg,
  'menu.background': g.bgFloat,
  'menu.foreground': g.fg,
  'menu.border': g.border,
  'menu.selectionBackground': g.bgSelection,
  'menu.selectionForeground': g.white,
  'menu.separatorBackground': g.border,

  // Activity bar
  'activityBar.background': g.bgDark,
  'activityBar.foreground': g.fg,
  'activityBar.inactiveForeground': g.fgSubtle,
  'activityBar.border': g.border,
  'activityBar.activeBorder': accent,
  'activityBar.activeBackground': g.bgFloat,
  'activityBar.activeFocusBorder': accent,
  'activityBar.dropBorder': accent,
  'activityBarBadge.background': alert,
  'activityBarBadge.foreground': g.white,
  'activityBarTop.foreground': g.fg,
  'activityBarTop.inactiveForeground': g.fgSubtle,
  'activityBarTop.activeBorder': accent,

  // Side bar
  'sideBar.background': g.bgDark,
  'sideBar.foreground': g.fgMuted,
  'sideBar.border': g.border,
  'sideBar.dropBackground': alpha(accent, 0.15),
  'sideBarTitle.foreground': g.fg,
  'sideBarSectionHeader.background': g.bgDark,
  'sideBarSectionHeader.foreground': g.fg,
  'sideBarSectionHeader.border': g.border,
  'sideBarActivityBarTop.border': g.border,
  'sideBarStickyScroll.background': g.bgDark,
  'sideBarStickyScroll.shadow': '#00000066',

  // Lists and trees
  'list.activeSelectionBackground': g.bgSelection,
  'list.activeSelectionForeground': g.white,
  'list.activeSelectionIconForeground': g.white,
  'list.inactiveSelectionBackground': g.bgFloat,
  'list.inactiveSelectionForeground': g.fg,
  'list.focusBackground': g.bgSelection,
  'list.focusForeground': g.white,
  'list.focusOutline': alpha(accent, 0.6),
  'list.inactiveFocusOutline': g.border,
  'list.hoverBackground': g.bgFloat,
  'list.hoverForeground': g.fg,
  'list.dropBackground': alpha(accent, 0.15),
  'list.highlightForeground': accent,
  'list.focusHighlightForeground': a.ice,
  'list.errorForeground': a.pink,
  'list.warningForeground': a.peach,
  'list.invalidItemForeground': a.pink,
  'list.deemphasizedForeground': g.fgSubtle,
  'list.filterMatchBackground': alpha(accent, 0.2),
  'list.filterMatchBorder': transparent,
  'listFilterWidget.background': g.bgFloat,
  'listFilterWidget.outline': accent,
  'listFilterWidget.noMatchesOutline': a.pink,
  'tree.indentGuidesStroke': g.border,
  'tree.inactiveIndentGuidesStroke': alpha(g.border, 0.6),
  'tree.tableColumnsBorder': g.border,

  // Editor groups and tabs
  'editorGroup.border': g.border,
  'editorGroup.dropBackground': alpha(accent, 0.12),
  'editorGroup.emptyBackground': g.bg,
  'editorGroupHeader.tabsBackground': g.bgDark,
  'editorGroupHeader.tabsBorder': g.border,
  'editorGroupHeader.noTabsBackground': g.bgDark,
  'editorGroupHeader.border': g.border,
  'tab.activeBackground': g.bg,
  'tab.activeForeground': g.fg,
  'tab.activeBorder': g.bg,
  'tab.activeBorderTop': accent,
  'tab.activeModifiedBorder': accent,
  'tab.inactiveBackground': g.bgDark,
  'tab.inactiveForeground': g.fgSubtle,
  'tab.inactiveModifiedBorder': alpha(accent, 0.5),
  'tab.unfocusedActiveBackground': g.bg,
  'tab.unfocusedActiveForeground': g.fgMuted,
  'tab.unfocusedActiveBorderTop': g.border,
  'tab.unfocusedInactiveBackground': g.bgDark,
  'tab.unfocusedInactiveForeground': g.fgSubtle,
  'tab.hoverBackground': g.bgFloat,
  'tab.hoverForeground': g.fg,
  'tab.unfocusedHoverBackground': g.bgFloat,
  'tab.border': g.border,
  'tab.lastPinnedBorder': g.bgSelection,
  'tab.dragAndDropBorder': accent,
  'tab.selectedBackground': g.bg,
  'tab.selectedForeground': g.fg,
  'tab.selectedBorderTop': accent,
  'breadcrumb.background': g.bg,
  'breadcrumb.foreground': g.fgSubtle,
  'breadcrumb.focusForeground': g.fg,
  'breadcrumb.activeSelectionForeground': g.fg,
  'breadcrumbPicker.background': g.bgFloat,

  // Editor
  'editor.background': g.bg,
  'editor.foreground': g.fg,
  'editorLineNumber.foreground': g.lineNr,
  'editorLineNumber.activeForeground': g.lineNrActive,
  'editorLineNumber.dimmedForeground': alpha(g.lineNr, 0.6),
  'editorCursor.foreground': g.fg,
  'editorCursor.background': g.bg,
  'editorMultiCursor.primary.foreground': g.fg,
  'editorMultiCursor.secondary.foreground': a.blueLight,
  'editor.lineHighlightBackground': g.bgLine,
  'editor.lineHighlightBorder': transparent,
  'editor.rangeHighlightBackground': alpha(accent, 0.08),
  'editor.symbolHighlightBackground': alpha(accent, 0.15),
  'editor.selectionBackground': g.bgSelection,
  'editor.inactiveSelectionBackground': alpha(g.bgSelection, 0.6),
  'editor.selectionHighlightBackground': alpha(accent, 0.15),
  'editor.selectionHighlightBorder': transparent,
  'editor.wordHighlightBackground': alpha(accent, 0.15),
  'editor.wordHighlightStrongBackground': alpha(a.rose, 0.18),
  'editor.wordHighlightTextBackground': alpha(accent, 0.15),
  'editor.findMatchBackground': alpha(a.peach, 0.35),
  'editor.findMatchBorder': a.peach,
  'editor.findMatchHighlightBackground': alpha(a.peach, 0.18),
  'editor.findMatchHighlightBorder': transparent,
  'editor.findRangeHighlightBackground': alpha(accent, 0.08),
  'editor.hoverHighlightBackground': alpha(accent, 0.12),
  'editor.linkedEditingBackground': alpha(a.rose, 0.12),
  'editor.foldBackground': alpha(accent, 0.08),
  'editor.foldPlaceholderForeground': g.fgMuted,
  'editor.placeholder.foreground': g.fgSubtle,
  'editorLink.activeForeground': a.ice,
  'editorWhitespace.foreground': alpha(g.lineNr, 0.6),
  'editorIndentGuide.background1': g.border,
  'editorIndentGuide.activeBackground1': g.lineNr,
  'editorRuler.foreground': g.border,
  'editorCodeLens.foreground': g.fgSubtle,
  'editorLightBulb.foreground': a.peach,
  'editorLightBulbAutoFix.foreground': accent,
  'editorLightBulbAi.foreground': a.purple,
  'editorInlayHint.foreground': g.fgSubtle,
  'editorInlayHint.background': alpha(g.bgFloat, 0.8),
  'editorInlayHint.typeForeground': g.fgSubtle,
  'editorInlayHint.parameterForeground': g.fgSubtle,
  'editorGhostText.foreground': g.fgSubtle,
  'editorUnnecessaryCode.opacity': '#000000a0',
  'editorStickyScroll.background': g.bg,
  'editorStickyScroll.shadow': '#00000066',
  'editorStickyScrollHover.background': g.bgFloat,
  'editorUnicodeHighlight.border': a.peach,

  // Brackets
  'editorBracketMatch.background': alpha(accent, 0.18),
  'editorBracketMatch.border': alpha(accent, 0.6),
  'editorBracketHighlight.foreground1': a.blue,
  'editorBracketHighlight.foreground2': a.purple,
  'editorBracketHighlight.foreground3': a.cyan,
  'editorBracketHighlight.foreground4': a.rose,
  'editorBracketHighlight.foreground5': a.ice,
  'editorBracketHighlight.foreground6': a.peach,
  'editorBracketHighlight.unexpectedBracket.foreground': a.pink,
  'editorBracketPairGuide.activeBackground1': alpha(a.blue, 0.5),
  'editorBracketPairGuide.activeBackground2': alpha(a.purple, 0.5),
  'editorBracketPairGuide.activeBackground3': alpha(a.cyan, 0.5),
  'editorBracketPairGuide.activeBackground4': alpha(a.rose, 0.5),
  'editorBracketPairGuide.activeBackground5': alpha(a.ice, 0.5),
  'editorBracketPairGuide.activeBackground6': alpha(a.peach, 0.5),

  // Diagnostics
  'editorError.foreground': a.pink,
  'editorWarning.foreground': a.peach,
  'editorInfo.foreground': accent,
  'editorHint.foreground': a.teal,
  'problemsErrorIcon.foreground': a.pink,
  'problemsWarningIcon.foreground': a.peach,
  'problemsInfoIcon.foreground': accent,

  // Gutter
  'editorGutter.background': g.bg,
  'editorGutter.modifiedBackground': accent,
  'editorGutter.addedBackground': a.green,
  'editorGutter.deletedBackground': a.pink,
  'editorGutter.foldingControlForeground': g.fgMuted,
  'editorGutter.commentRangeForeground': g.fgSubtle,

  // Overview ruler
  'editorOverviewRuler.border': transparent,
  'editorOverviewRuler.background': g.bg,
  'editorOverviewRuler.modifiedForeground': alpha(accent, 0.7),
  'editorOverviewRuler.addedForeground': alpha(a.green, 0.7),
  'editorOverviewRuler.deletedForeground': alpha(a.pink, 0.7),
  'editorOverviewRuler.errorForeground': a.pink,
  'editorOverviewRuler.warningForeground': a.peach,
  'editorOverviewRuler.infoForeground': accent,
  'editorOverviewRuler.findMatchForeground': alpha(a.peach, 0.8),
  'editorOverviewRuler.selectionHighlightForeground': alpha(accent, 0.6),
  'editorOverviewRuler.wordHighlightForeground': alpha(accent, 0.6),
  'editorOverviewRuler.wordHighlightStrongForeground': alpha(a.rose, 0.6),
  'editorOverviewRuler.bracketMatchForeground': alpha(accent, 0.6),

  // Widgets: find, suggest, hover, peek
  'editorWidget.background': g.bgFloat,
  'editorWidget.foreground': g.fg,
  'editorWidget.border': g.border,
  'editorWidget.resizeBorder': accent,
  'editorSuggestWidget.background': g.bgFloat,
  'editorSuggestWidget.border': g.border,
  'editorSuggestWidget.foreground': g.fg,
  'editorSuggestWidget.selectedBackground': g.bgSelection,
  'editorSuggestWidget.selectedForeground': g.white,
  'editorSuggestWidget.selectedIconForeground': g.white,
  'editorSuggestWidget.highlightForeground': accent,
  'editorSuggestWidget.focusHighlightForeground': a.ice,
  'editorSuggestWidgetStatus.foreground': g.fgSubtle,
  'editorHoverWidget.background': g.bgFloat,
  'editorHoverWidget.foreground': g.fg,
  'editorHoverWidget.border': g.border,
  'editorHoverWidget.highlightForeground': accent,
  'editorHoverWidget.statusBarBackground': g.bgDark,
  'editorMarkerNavigation.background': g.bgFloat,
  'editorMarkerNavigationError.background': a.pink,
  'editorMarkerNavigationError.headerBackground': alpha(a.pink, 0.12),
  'editorMarkerNavigationWarning.background': a.peach,
  'editorMarkerNavigationWarning.headerBackground': alpha(a.peach, 0.12),
  'editorMarkerNavigationInfo.background': accent,
  'editorMarkerNavigationInfo.headerBackground': alpha(accent, 0.12),
  'debugExceptionWidget.background': g.bgFloat,
  'debugExceptionWidget.border': a.pink,
  'peekView.border': accent,
  'peekViewTitle.background': g.bgFloat,
  'peekViewTitleLabel.foreground': g.fg,
  'peekViewTitleDescription.foreground': g.fgMuted,
  'peekViewEditor.background': g.bgDark,
  'peekViewEditorGutter.background': g.bgDark,
  'peekViewEditor.matchHighlightBackground': alpha(a.peach, 0.3),
  'peekViewEditor.matchHighlightBorder': transparent,
  'peekViewEditorStickyScroll.background': g.bgDark,
  'peekViewResult.background': g.bgFloat,
  'peekViewResult.fileForeground': g.fg,
  'peekViewResult.lineForeground': g.fgMuted,
  'peekViewResult.matchHighlightBackground': alpha(a.peach, 0.3),
  'peekViewResult.selectionBackground': g.bgSelection,
  'peekViewResult.selectionForeground': g.white,

  // Minimap
  'minimap.background': g.bg,
  'minimap.foregroundOpacity': '#000000c0',
  'minimap.selectionHighlight': alpha(g.fg, 0.35),
  'minimap.selectionOccurrenceHighlight': alpha(accent, 0.4),
  'minimap.findMatchHighlight': alpha(a.peach, 0.6),
  'minimap.errorHighlight': alpha(a.pink, 0.8),
  'minimap.warningHighlight': alpha(a.peach, 0.8),
  'minimap.infoHighlight': alpha(accent, 0.8),
  'minimapGutter.addedBackground': a.green,
  'minimapGutter.modifiedBackground': accent,
  'minimapGutter.deletedBackground': a.pink,
  'minimapSlider.background': alpha(g.fgSubtle, 0.15),
  'minimapSlider.hoverBackground': alpha(g.fgSubtle, 0.25),
  'minimapSlider.activeBackground': alpha(g.fgSubtle, 0.35),

  // Scrollbars
  'scrollbar.shadow': '#00000066',
  'scrollbarSlider.background': alpha(g.fgSubtle, 0.25),
  'scrollbarSlider.hoverBackground': alpha(g.fgSubtle, 0.4),
  'scrollbarSlider.activeBackground': alpha(g.fgSubtle, 0.55),

  // Diff editor
  'diffEditor.insertedTextBackground': alpha(a.green, 0.18),
  'diffEditor.removedTextBackground': alpha(a.pink, 0.18),
  'diffEditor.insertedLineBackground': alpha(a.green, 0.08),
  'diffEditor.removedLineBackground': alpha(a.pink, 0.08),
  'diffEditor.border': g.border,
  'diffEditor.diagonalFill': alpha(g.border, 0.8),
  'diffEditor.unchangedRegionBackground': g.bgDark,
  'diffEditor.unchangedRegionForeground': g.fgMuted,
  'diffEditor.unchangedCodeBackground': alpha(g.bgFloat, 0.5),
  'diffEditor.move.border': alpha(accent, 0.5),
  'diffEditor.moveActive.border': a.peach,
  'diffEditorGutter.insertedLineBackground': alpha(a.green, 0.2),
  'diffEditorGutter.removedLineBackground': alpha(a.pink, 0.2),
  'diffEditorOverview.insertedForeground': alpha(a.green, 0.6),
  'diffEditorOverview.removedForeground': alpha(a.pink, 0.6),
  'multiDiffEditor.headerBackground': g.bgDark,
  'multiDiffEditor.background': g.bg,
  'multiDiffEditor.border': g.border,

  // Merge conflicts
  'merge.currentHeaderBackground': alpha(a.green, 0.35),
  'merge.currentContentBackground': alpha(a.green, 0.12),
  'merge.incomingHeaderBackground': alpha(accent, 0.35),
  'merge.incomingContentBackground': alpha(accent, 0.12),
  'merge.commonHeaderBackground': alpha(g.fgSubtle, 0.35),
  'merge.commonContentBackground': alpha(g.fgSubtle, 0.12),
  'merge.border': g.border,
  'editorOverviewRuler.currentContentForeground': alpha(a.green, 0.6),
  'editorOverviewRuler.incomingContentForeground': alpha(accent, 0.6),
  'editorOverviewRuler.commonContentForeground': alpha(g.fgSubtle, 0.6),
  'mergeEditor.change.background': alpha(accent, 0.12),
  'mergeEditor.change.word.background': alpha(accent, 0.25),
  'mergeEditor.conflict.unhandledUnfocused.border': alpha(a.peach, 0.6),
  'mergeEditor.conflict.unhandledFocused.border': a.peach,
  'mergeEditor.conflict.handledUnfocused.border': alpha(a.green, 0.4),
  'mergeEditor.conflict.handledFocused.border': a.green,

  // Git decorations
  'gitDecoration.addedResourceForeground': a.green,
  'gitDecoration.modifiedResourceForeground': accent,
  'gitDecoration.deletedResourceForeground': a.pink,
  'gitDecoration.renamedResourceForeground': a.cyan,
  'gitDecoration.untrackedResourceForeground': a.green,
  'gitDecoration.ignoredResourceForeground': g.fgSubtle,
  'gitDecoration.conflictingResourceForeground': a.peach,
  'gitDecoration.submoduleResourceForeground': a.teal,
  'gitDecoration.stageModifiedResourceForeground': a.ice,
  'gitDecoration.stageDeletedResourceForeground': a.rose,
  'scmGraph.historyItemHoverLabelForeground': g.bg,
  'scmGraph.foreground1': a.blue,
  'scmGraph.foreground2': a.rose,
  'scmGraph.foreground3': a.teal,
  'scmGraph.foreground4': a.purple,
  'scmGraph.foreground5': a.peach,
  'scmGraph.historyItemRefColor': accent,
  'scmGraph.historyItemRemoteRefColor': a.purple,
  'scmGraph.historyItemBaseRefColor': a.peach,

  // Panel
  'panel.background': g.bgDark,
  'panel.border': g.border,
  'panel.dropBorder': accent,
  'panelTitle.activeForeground': g.fg,
  'panelTitle.inactiveForeground': g.fgSubtle,
  'panelTitle.activeBorder': accent,
  'panelInput.border': g.border,
  'panelSection.border': g.border,
  'panelSectionHeader.background': g.bgDark,
  'panelSectionHeader.foreground': g.fg,
  'panelStickyScroll.background': g.bgDark,
  'outputView.background': g.bgDark,

  // Terminal
  'terminal.background': g.bgDark,
  'terminal.foreground': g.fg,
  'terminal.border': g.border,
  'terminal.selectionBackground': g.bgSelection,
  'terminal.inactiveSelectionBackground': alpha(g.bgSelection, 0.6),
  'terminal.findMatchBackground': alpha(a.peach, 0.35),
  'terminal.findMatchHighlightBackground': alpha(a.peach, 0.18),
  'terminalCursor.foreground': g.fg,
  'terminalCursor.background': g.bgDark,
  'terminal.dropBackground': alpha(accent, 0.15),
  'terminal.tab.activeBorder': accent,
  'terminalCommandDecoration.defaultBackground': g.fgSubtle,
  'terminalCommandDecoration.successBackground': a.green,
  'terminalCommandDecoration.errorBackground': a.pink,
  'terminalOverviewRuler.cursorForeground': alpha(accent, 0.6),
  'terminalOverviewRuler.findMatchForeground': alpha(a.peach, 0.6),
  'terminalStickyScroll.background': g.bgDark,
  'terminal.ansiBlack': ansi.black,
  'terminal.ansiRed': ansi.red,
  'terminal.ansiGreen': ansi.green,
  'terminal.ansiYellow': ansi.yellow,
  'terminal.ansiBlue': ansi.blue,
  'terminal.ansiMagenta': ansi.magenta,
  'terminal.ansiCyan': ansi.cyan,
  'terminal.ansiWhite': ansi.white,
  'terminal.ansiBrightBlack': ansi.brightBlack,
  'terminal.ansiBrightRed': ansi.brightRed,
  'terminal.ansiBrightGreen': ansi.brightGreen,
  'terminal.ansiBrightYellow': ansi.brightYellow,
  'terminal.ansiBrightBlue': ansi.brightBlue,
  'terminal.ansiBrightMagenta': ansi.brightMagenta,
  'terminal.ansiBrightCyan': ansi.brightCyan,
  'terminal.ansiBrightWhite': ansi.brightWhite,

  // Status bar
  'statusBar.background': g.bgDark,
  'statusBar.foreground': g.fgMuted,
  'statusBar.border': g.border,
  'statusBar.focusBorder': accent,
  'statusBar.noFolderBackground': g.bgDark,
  'statusBar.noFolderForeground': g.fgMuted,
  'statusBar.noFolderBorder': g.border,
  'statusBar.debuggingBackground': a.peach,
  'statusBar.debuggingForeground': g.bgDark,
  'statusBar.debuggingBorder': a.peach,
  'statusBarItem.hoverBackground': g.bgFloat,
  'statusBarItem.hoverForeground': g.fg,
  'statusBarItem.activeBackground': g.bgSelection,
  'statusBarItem.focusBorder': accent,
  'statusBarItem.remoteBackground': accent,
  'statusBarItem.remoteForeground': g.bgDark,
  'statusBarItem.remoteHoverBackground': a.blueLight,
  'statusBarItem.remoteHoverForeground': g.bgDark,
  'statusBarItem.prominentBackground': g.bgSelection,
  'statusBarItem.prominentForeground': g.fg,
  'statusBarItem.prominentHoverBackground': g.bgFloat,
  'statusBarItem.errorBackground': alert,
  'statusBarItem.errorForeground': g.white,
  'statusBarItem.errorHoverBackground': a.rose,
  'statusBarItem.warningBackground': a.peach,
  'statusBarItem.warningForeground': g.bgDark,
  'statusBarItem.warningHoverBackground': a.peach,
  'statusBarItem.offlineBackground': a.pink,
  'statusBarItem.offlineForeground': g.white,
  'statusBarItem.compactHoverBackground': g.bgSelection,

  // Badges
  'badge.background': alert,
  'badge.foreground': g.white,
  'activityWarningBadge.background': a.peach,
  'activityWarningBadge.foreground': g.bgDark,
  'activityErrorBadge.background': alert,
  'activityErrorBadge.foreground': g.white,

  // Buttons
  'button.background': accent,
  'button.foreground': g.bgDark,
  'button.hoverBackground': a.blueLight,
  'button.border': transparent,
  'button.separator': alpha(g.bgDark, 0.4),
  'button.secondaryBackground': g.bgSelection,
  'button.secondaryForeground': g.fg,
  'button.secondaryHoverBackground': g.lineNr,
  'extensionButton.background': accent,
  'extensionButton.foreground': g.bgDark,
  'extensionButton.hoverBackground': a.blueLight,
  'extensionButton.prominentBackground': accent,
  'extensionButton.prominentForeground': g.bgDark,
  'extensionButton.prominentHoverBackground': a.blueLight,
  'extensionBadge.remoteBackground': accent,
  'extensionBadge.remoteForeground': g.bgDark,
  'extensionIcon.starForeground': a.peach,
  'extensionIcon.verifiedForeground': accent,
  'extensionIcon.preReleaseForeground': a.rose,
  'extensionIcon.sponsorForeground': a.rose,

  // Inputs and dropdowns
  'input.background': g.bgFloat,
  'input.foreground': g.fg,
  'input.border': g.border,
  'input.placeholderForeground': g.fgSubtle,
  'inputOption.activeBackground': alpha(accent, 0.25),
  'inputOption.activeBorder': alpha(accent, 0.6),
  'inputOption.activeForeground': g.white,
  'inputOption.hoverBackground': g.bgSelection,
  'inputValidation.errorBackground': g.bgFloat,
  'inputValidation.errorForeground': g.fg,
  'inputValidation.errorBorder': a.pink,
  'inputValidation.warningBackground': g.bgFloat,
  'inputValidation.warningForeground': g.fg,
  'inputValidation.warningBorder': a.peach,
  'inputValidation.infoBackground': g.bgFloat,
  'inputValidation.infoForeground': g.fg,
  'inputValidation.infoBorder': accent,
  'dropdown.background': g.bgFloat,
  'dropdown.listBackground': g.bgFloat,
  'dropdown.foreground': g.fg,
  'dropdown.border': g.border,
  'checkbox.background': g.bgFloat,
  'checkbox.foreground': g.fg,
  'checkbox.border': g.border,
  'checkbox.selectBackground': g.bgFloat,
  'checkbox.selectBorder': accent,
  'radio.activeBackground': alpha(accent, 0.25),
  'radio.activeForeground': g.white,
  'radio.activeBorder': alpha(accent, 0.6),
  'radio.inactiveBorder': g.border,
  'radio.inactiveHoverBackground': g.bgSelection,
  'keybindingLabel.background': g.bgSelection,
  'keybindingLabel.foreground': g.fg,
  'keybindingLabel.border': g.border,
  'keybindingLabel.bottomBorder': g.bgDark,
  'keybindingTable.headerBackground': g.bgFloat,
  'keybindingTable.rowsBackground': g.bgDark,

  // Quick input / command palette
  'quickInput.background': g.bgFloat,
  'quickInput.foreground': g.fg,
  'quickInputTitle.background': g.bgDark,
  'quickInputList.focusBackground': g.bgSelection,
  'quickInputList.focusForeground': g.white,
  'quickInputList.focusIconForeground': g.white,
  'pickerGroup.foreground': accent,
  'pickerGroup.border': g.border,

  // Notifications
  'notifications.background': g.bgFloat,
  'notifications.foreground': g.fg,
  'notifications.border': g.border,
  'notificationCenter.border': g.border,
  'notificationCenterHeader.background': g.bgDark,
  'notificationCenterHeader.foreground': g.fg,
  'notificationToast.border': g.border,
  'notificationLink.foreground': accent,
  'notificationsErrorIcon.foreground': a.pink,
  'notificationsWarningIcon.foreground': a.peach,
  'notificationsInfoIcon.foreground': accent,

  // Banner
  'banner.background': g.bgSelection,
  'banner.foreground': g.fg,
  'banner.iconForeground': accent,

  // Debug
  'debugToolBar.background': g.bgFloat,
  'debugToolBar.border': g.border,
  'debugIcon.breakpointForeground': a.pink,
  'debugIcon.breakpointDisabledForeground': g.fgSubtle,
  'debugIcon.breakpointUnverifiedForeground': a.rose,
  'debugIcon.breakpointCurrentStackframeForeground': a.peach,
  'debugIcon.breakpointStackframeForeground': a.green,
  'debugIcon.startForeground': a.green,
  'debugIcon.pauseForeground': accent,
  'debugIcon.stopForeground': a.pink,
  'debugIcon.disconnectForeground': a.pink,
  'debugIcon.restartForeground': a.green,
  'debugIcon.stepOverForeground': accent,
  'debugIcon.stepIntoForeground': accent,
  'debugIcon.stepOutForeground': accent,
  'debugIcon.stepBackForeground': accent,
  'debugIcon.continueForeground': accent,
  'debugConsole.infoForeground': accent,
  'debugConsole.warningForeground': a.peach,
  'debugConsole.errorForeground': a.pink,
  'debugConsole.sourceForeground': g.fgMuted,
  'debugConsoleInputIcon.foreground': accent,
  'debugTokenExpression.name': a.ice,
  'debugTokenExpression.value': g.fg,
  'debugTokenExpression.string': a.purple,
  'debugTokenExpression.number': a.peach,
  'debugTokenExpression.boolean': a.teal,
  'debugTokenExpression.error': a.pink,
  'debugTokenExpression.type': a.sky,
  'debugView.stateLabelForeground': g.fg,
  'debugView.stateLabelBackground': g.bgSelection,
  'debugView.valueChangedHighlight': alpha(accent, 0.4),
  'editor.stackFrameHighlightBackground': alpha(a.peach, 0.15),
  'editor.focusedStackFrameHighlightBackground': alpha(a.green, 0.15),

  // Testing
  'testing.iconPassed': a.green,
  'testing.iconFailed': a.pink,
  'testing.iconErrored': a.pink,
  'testing.iconQueued': a.peach,
  'testing.iconUnset': g.fgSubtle,
  'testing.iconSkipped': g.fgSubtle,
  'testing.runAction': a.green,
  'testing.peekBorder': a.pink,
  'testing.peekHeaderBackground': alpha(a.pink, 0.1),
  'testing.message.error.lineBackground': alpha(a.pink, 0.1),
  'testing.message.info.decorationForeground': g.fgSubtle,
  'testing.coveredBackground': alpha(a.green, 0.12),
  'testing.coveredGutterBackground': alpha(a.green, 0.5),
  'testing.uncoveredBackground': alpha(a.pink, 0.12),
  'testing.uncoveredGutterBackground': alpha(a.pink, 0.5),

  // Notebooks
  'notebook.cellBorderColor': g.border,
  'notebook.focusedCellBorder': alpha(accent, 0.6),
  'notebook.cellEditorBackground': g.bgDark,
  'notebook.cellToolbarSeparator': g.border,
  'notebook.focusedEditorBorder': alpha(accent, 0.6),
  'notebook.selectedCellBackground': g.bgFloat,
  'notebook.selectedCellBorder': g.border,
  'notebook.cellHoverBackground': alpha(g.bgFloat, 0.6),
  'notebook.outputContainerBackgroundColor': g.bgDark,
  'notebookStatusSuccessIcon.foreground': a.green,
  'notebookStatusErrorIcon.foreground': a.pink,
  'notebookStatusRunningIcon.foreground': accent,

  // Settings editor
  'settings.headerForeground': g.fg,
  'settings.modifiedItemIndicator': accent,
  'settings.focusedRowBackground': alpha(g.bgFloat, 0.6),
  'settings.rowHoverBackground': alpha(g.bgFloat, 0.4),
  'settings.focusedRowBorder': alpha(accent, 0.6),
  'settings.headerBorder': g.border,
  'settings.sashBorder': g.border,
  'settings.dropdownBackground': g.bgFloat,
  'settings.dropdownBorder': g.border,
  'settings.checkboxBackground': g.bgFloat,
  'settings.checkboxBorder': g.border,
  'settings.textInputBackground': g.bgFloat,
  'settings.textInputBorder': g.border,
  'settings.numberInputBackground': g.bgFloat,
  'settings.numberInputBorder': g.border,

  // Welcome page and walkthroughs
  'welcomePage.background': g.bg,
  'welcomePage.tileBackground': g.bgFloat,
  'welcomePage.tileHoverBackground': g.bgSelection,
  'welcomePage.tileBorder': g.border,
  'welcomePage.progress.background': g.bgSelection,
  'welcomePage.progress.foreground': accent,
  'walkThrough.embeddedEditorBackground': g.bgDark,

  // Chat
  'chat.requestBackground': g.bgFloat,
  'chat.requestBorder': g.border,
  'chat.slashCommandBackground': alpha(accent, 0.2),
  'chat.slashCommandForeground': accent,
  'chat.avatarBackground': g.bgSelection,
  'chat.avatarForeground': g.fg,
  'inlineChat.background': g.bgFloat,
  'inlineChat.border': g.border,
  'inlineChatInput.background': g.bg,
  'inlineChatInput.border': g.border,
  'inlineChatInput.focusBorder': alpha(accent, 0.6),

  // Symbol icons
  'symbolIcon.arrayForeground': a.cyan,
  'symbolIcon.booleanForeground': a.teal,
  'symbolIcon.classForeground': a.sky,
  'symbolIcon.colorForeground': a.peach,
  'symbolIcon.constantForeground': a.peach,
  'symbolIcon.constructorForeground': a.sky,
  'symbolIcon.enumeratorForeground': a.sky,
  'symbolIcon.enumeratorMemberForeground': a.peach,
  'symbolIcon.eventForeground': a.ice,
  'symbolIcon.fieldForeground': a.ice,
  'symbolIcon.fileForeground': g.fgMuted,
  'symbolIcon.folderForeground': g.fgMuted,
  'symbolIcon.functionForeground': a.rose,
  'symbolIcon.interfaceForeground': a.sky,
  'symbolIcon.keyForeground': a.ice,
  'symbolIcon.keywordForeground': a.blue,
  'symbolIcon.methodForeground': a.teal,
  'symbolIcon.moduleForeground': a.teal,
  'symbolIcon.namespaceForeground': a.teal,
  'symbolIcon.nullForeground': a.teal,
  'symbolIcon.numberForeground': a.peach,
  'symbolIcon.objectForeground': a.sky,
  'symbolIcon.operatorForeground': a.blueLight,
  'symbolIcon.packageForeground': a.teal,
  'symbolIcon.propertyForeground': a.ice,
  'symbolIcon.referenceForeground': a.ice,
  'symbolIcon.snippetForeground': a.purple,
  'symbolIcon.stringForeground': a.purple,
  'symbolIcon.structForeground': a.sky,
  'symbolIcon.textForeground': g.fg,
  'symbolIcon.typeParameterForeground': a.sky,
  'symbolIcon.unitForeground': a.peach,
  'symbolIcon.variableForeground': g.fg,

  // Charts
  'charts.foreground': g.fg,
  'charts.lines': g.fgSubtle,
  'charts.red': a.pink,
  'charts.blue': a.blue,
  'charts.yellow': a.peach,
  'charts.orange': a.peach,
  'charts.green': a.green,
  'charts.purple': a.purple,
};
